#!/bin/bash
# commands to run in fresh AWS EC2 instance to configure things

# installs
sudo yum update -y
sudo yum install -y tree htop git java-1.8.0-openjdk python3 docker
curl -s https://get.nextflow.io | bash && sudo mv nextflow /usr/bin/
# sudo amazon-linux-extras install java-openjdk11

# configurations
git config --global user.name "Stephen Kelly"
git config --global user.email stevekm@users.noreply.github.com
git clone https://github.com/stevekm/dotfiles.git
echo 'if [ -f ~/dotfiles/bashrc_extras ]; then . ~/dotfiles/bashrc_extras; fi' >> .bashrc
