#!/bin/bash
# commands to run in fresh AWS EC2 instance to configure things
sudo yum update
sudo yum install git
git config --global user.name "Stephen Kelly"
git config --global user.email stevekm@users.noreply.github.com
git clone https://github.com/stevekm/dotfiles.git
echo 'if [ -f ~/dotfiles/bashrc_extras ]; then . ~/dotfiles/bashrc_extras; fi' >> .bashrc
