#!/bin/bash
THIS_DIR="$(dirname $BASH_SOURCE)"

source "${THIS_DIR}/console.sh"
source "${THIS_DIR}/console.colors.sh"
source "${THIS_DIR}/aliases.sh"
source "${THIS_DIR}/aliases.git.sh"
# source "${THIS_DIR}/aliases.slurm.sh"
# source "${THIS_DIR}/aliases.bigpurple.sh"
source "${THIS_DIR}/ssh_settings.sh"
